project:
  type: website

website:
  title: "Chasing DevOps Nirvana"
  navbar:
    right:
      - about.qmd
      - icon: file-text
        text: Résumé
        href: /resume/resume.pdf
      - icon: github
        href: https://github.com/mbuotidem
      - icon: twitter
        href: https://twitter.com/mbuotidemisaac
      - icon: linkedin
        href: https://www.linkedin.com/in/miisaac/
      - icon: stack-overflow
        href: https://stackoverflow.com/users/7179900/mbuotidem-isaac
format:
  html:
    theme: cosmo
    css: styles.css



