on: 
  push:
  workflow_dispatch:
    inputs:
      fromRunme:
        description: "Whether run locally"
        required: false
        type: string
        default: yes


name: Build and deploy GH Pages
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}